### ISSUE TITLE
Incompatible with Rack 2.0.8 

### ISSUE THREAD

**Issue by iain** [mwpastore/rack-session-smart_cookie#2]
Today Rack 2.0.8 got released. It is not compatible with rack-session-smart_cookie.

Here is the backtrace:

```
#<NoMethodError: undefined method `to_msgpack' for #<Rack::Session::SessionId:0x00007fe7e3362a68>>
/usr/local/lib/ruby/gems/2.6.0/gems/rack-session-smart_cookie-0.2.0/lib/rack/session/smart_cookie.rb:59:in `write'
/usr/local/lib/ruby/gems/2.6.0/gems/rack-session-smart_cookie-0.2.0/lib/rack/session/smart_cookie.rb:59:in `encode'
/usr/local/lib/ruby/gems/2.6.0/gems/rack-session-smart_cookie-0.2.0/lib/rack/session/smart_cookie.rb:145:in `write_session'
/usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:381:in `commit_session'
/usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:261:in `context'
/usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.8/lib/rack/session/abstract/id.rb:253:in `call'
```

**Comment by mwpastore** [comment]
Hi @iain, thank you for reporting this issue. I'll take a look at it over the weekend.
